export const rows = [
  {
    id: 1,
    name: "Mohamed",
    email: "mohamed@gmail.com",
    age: 24,
    phone: "+20 1020 9938",
    access: "User",
  },
  {
    id: 2,
    name: "Ahmed",
    email: "ahmed@gmail.com",
    age: 30,
    phone: "+20 1190 3434",
    access: "User",
  },
  {
    id: 3,
    name: "Mostafa",
    email: "mostafa@gmail.com",
    age: 38,
    phone: "+20 1245 3493",
    access: "User",
  },
  {
    id: 4,
    name: "Fatma",
    email: "fatma@gmail.com",
    age: 40,
    phone: "+20 1554 2323",
    access: "Admin",
  },
  {
    id: 5,
    name: "Ali",
    email: "ali@gmail.com",
    age: 45,
    phone: "+20 1012 3455",
    access: "Admin",
  },
  {
    id: 6,
    name: "Nada",
    email: "nada@gmail.com",
    age: 22,
    phone: "+20 1134 5566",
    access: "Admin",
  },
  {
    id: 7,
    name: "Barakat",
    email: "barakat@gmail.com",
    age: 50,
    phone: "+20 1068 6124",
    access: "Manager",
  },
  {
    id: 8,
    name: "Sayed",
    email: "sayed@gmail.com",
    age: 39,
    phone: "+20 1110 8435",
    access: "Admin",
  },
  {
    id: 9,
    name: "Mazen",
    email: "mazen@gmail.com",
    age: 60,
    phone: "+20 1010 5133",
    access: "Manager",
  },
];


